export const jwtConstants = {
    secret:'DO NOT USE THIS VALUE.INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
    refresh_secret:"DO NOT USE THIS VALUE AS REFRESH TOKEN"
}